### PR TITLE
Update Rails version to 7.1

### PR DESCRIPTION
**Pull request by kennyadsl**
### WHY are these changes introduced?

We want to start new applications using the latest Rails version available.

### WHAT is this pull request doing?

This PR: 

- updates Rails to version 7.1 in the Gemfile
- runs  `bin/rails app:update` following the proposed process
- switch `config.load_defaults` to 7.1
- runs `rubocop -A` to have the code uniform across the project (I can also move this change to another PR if needed)

## Checklist

**Note**: once this PR is merged, it becomes a new release for this template.

- [ ] I have added/updated tests for this change
- [ ] I have made changes to the `README.md` file and other related documentation, if applicable

### CODE REVIEW

**Comment by kennyadsl** [comment]
I have signed the CLA!

**Review by paulomarg — APPROVED** [review]
All of the changes seem sensible, I was able to create an app with this and run it. LGTM!

**Comment by paulomarg** [comment]
Thanks for contributing!

**Comment by remy727** [comment]
`bin` and `db` directory was excluded but Rubocop updated files.

```yml
inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "test/tmp/**/*"
    - "vendor/bundle/**/*"

Style/MethodCallWithArgsParentheses:
  Exclude:
    - "**/Gemfile"
    - "test/**/*"

Style/ClassAndModuleChildren:
  Exclude:
    - "test/**/*"
```

**Comment by kennyadsl** [comment]
@remy727 got it, I think you are right, I can fix this with a new PR.

**Pull request merged**
