### PR TITLE
[FIX] Adding openssl-dev required by rails 7.x to default alpine package install

### LINKED ISSUE #37: Heroku Deployment not working with initial build
# Issue summary
I followed all the step for deployment on both Heroku and fly.io, but get the same error for build failing. Again no changes added only checking if production deployment works with template.

## Expected behavior

What do you think should happen?
It should deploy with no issues.

## Actual behavior

What actually happens?
Build errors occur on Heroku deployment. Error message: An error occurred while installing openssl (3.0.1), and Bundler cannot continue.

Gemfile:
```
# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.3"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

gem "tzinfo-data"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"

  gem "rubocop"
  gem "rubocop-shopify"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end

gem "shopify_app", "~> 20.1"
```

Dockerfile:
```
FROM ruby:3.1-alpine

ARG SHOPIFY_API_KEY
ENV SHOPIFY_API_KEY=$SHOPIFY_API_KEY

RUN apk update && apk add nodejs npm git build-base sqlite-dev gcompat bash
WORKDIR /app

COPY web .

RUN cd frontend && npm install
RUN bundle install

RUN cd frontend && npm run build
RUN rake build:all

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
```

Error Output:
```
remote: Installing turbo-rails 1.1.1
remote: Fetching web-console 4.2.0
remote: Installing web-console 4.2.0
remote: Fetching rails 7.0.4
remote: Installing rails 7.0.4
remote: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
remote: 
remote:     current directory: /usr/local/bundle/gems/openssl-3.0.1/ext/openssl
remote: /usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r
remote: ./siteconf20220912-1-rorgd8.rb extconf.rb
remote: checking for rb_io_maybe_wait()... yes
remote: checking for t_open() in -lnsl... no
remote: checking for socket() in -lsocket... no
remote: checking for openssl/ssl.h... no
remote: *** extconf.rb failed ***
remote: Could not create Makefile due to some reason, probably lack of necessary
remote: libraries and/or headers.  Check the mkmf.log file for more details.  You may
remote: need configuration options.
remote: 
remote: Provided configuration options:
remote:         --with-opt-dir
remote:         --without-opt-dir
remote:         --with-opt-include
remote:         --without-opt-include=${opt-dir}/include
remote:         --with-opt-lib
remote:         --without-opt-lib=${opt-dir}/lib
remote:         --with-make-prog
remote:         --without-make-prog
remote:         --srcdir=.
remote:         --curdir
remote:         --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
remote:         --with-openssl-dir
remote:         --without-openssl-dir
remote:         --with-openssl-include
remote:         --without-openssl-include=${openssl-dir}/include
remote:         --with-openssl-lib
remote:         --without-openssl-lib=${openssl-dir}/lib
remote:         --with-kerberos-dir
remote:         --without-kerberos-dir
remote:         --with-kerberos-include
remote:         --without-kerberos-include=${kerberos-dir}/include
remote:         --with-kerberos-lib
remote:         --without-kerberos-lib=${kerberos-dir}/lib
remote:         --with-debug
remote:         --without-debug
remote:         --enable-debug
remote:         --disable-debug
remote:         --with-nsl-dir
remote:         --without-nsl-dir
remote:         --with-nsl-include
remote:         --without-nsl-include=${nsl-dir}/include
remote:         --with-nsl-lib
remote:         --without-nsl-lib=${nsl-dir}/lib
remote:         --with-nsllib
remote:         --without-nsllib
remote:         --with-socket-dir
remote:         --without-socket-dir
remote:         --with-socket-include
remote:         --without-socket-include=${socket-dir}/include
remote:         --with-socket-lib
remote:         --without-socket-lib=${socket-dir}/lib
remote:         --with-socketlib
remote:         --without-socketlib
remote:         --with-openssl-config
remote:         --without-openssl-config
remote:         --with-pkg-config
remote:         --without-pkg-config
remote: extconf.rb:100:in `<main>': OpenSSL library could not be found. You might want
remote: to use --with-openssl-dir=<dir> option to specify the prefix where OpenSSL is
remote: installed. (RuntimeError)
remote: 
remote: To see why this extension failed to compile, please check the mkmf.log which can
remote: be found here:
remote: 
remote:   /usr/local/bundle/extensions/x86_64-linux-musl/3.1.0/openssl-3.0.1/mkmf.log
remote: 
remote: extconf failed, exit code 1
remote: 
remote: Gem files will remain installed in /usr/local/bundle/gems/openssl-3.0.1 for
remote: inspection.
remote: Results logged to
remote: /usr/local/bundle/extensions/x86_64-linux-musl/3.1.0/openssl-3.0.1/gem_make.out
remote: 
remote:   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
remote: /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in
remote: build'
remote:   /usr/local/lib/ruby/3.1.0/tempfile.rb:317:in `open'
remote:   /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
remote:   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
remote: /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in
remote: build_extensions'
remote:   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
remote:   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
remote:   /usr/local/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
remote: /usr/local/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:71:in
remote: `build_extensions'
remote:   /usr/local/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:28:in `install'
remote:   /usr/local/lib/ruby/3.1.0/bundler/source/rubygems.rb:204:in `install'
remote:   /usr/local/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:54:in `install'
remote: /usr/local/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:16:in
remote: `install_from_spec'
remote: /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:186:in
remote: `do_install'
remote: /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:177:in
remote: `block in worker_pool'
remote:   /usr/local/lib/ruby/3.1.0/bundler/worker.rb:62:in `apply_func'
remote:   /usr/local/lib/ruby/3.1.0/bundler/worker.rb:57:in `block in process_queue'
remote:   /usr/local/lib/ruby/3.1.0/bundler/worker.rb:54:in `loop'
remote:   /usr/local/lib/ruby/3.1.0/bundler/worker.rb:54:in `process_queue'
remote: /usr/local/lib/ruby/3.1.0/bundler/worker.rb:91:in `block (2 levels) in
remote: create_threads'
remote: 
remote: An error occurred while installing openssl (3.0.1), and Bundler cannot continue.
remote: 
remote: In Gemfile:
remote:   shopify_app was resolved to 20.1.1, which depends on
remote:     shopify_api was resolved to 11.1.0, which depends on
remote:       openssl
remote: The command '/bin/sh -c bundle install' returned a non-zero code: 5
remote: 
remote: Verifying deploy...
remote: 
remote: !       Push rejected to shopify-heroku-test.
remote: 
To https://git.heroku.com/shopify-heroku-test.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/shopify-heroku-test.git'

```

### PR DESCRIPTION
**Pull request by gcaprio**
### WHY are these changes introduced?

The current version of rails referenced in the Gemfile requires compiling openssl on alpine. However, the contained Docker file does not add openssl to the container, so the installation errors out. 

Fixes #37

### WHAT is this pull request doing?

Adding the openssl-dev package to the default container install

## Checklist

- [-] I have added/updated tests for this change
- [-] I have made changes to the `README.md` file and other related documentation, if applicable

### CODE REVIEW

**Comment by kenzan100** [comment]
+1 on this

**Comment by odessy** [comment]
+1 on this

**Comment by gcaprio** [comment]
sounds good @miguelperez my PR was from way back in Sept '22 so that commit wasn't in yet but glad it's fixed.

**Comment by mkevinosullivan** [comment]
Closing this PR as the change was included in https://github.com/Shopify/shopify-app-template-ruby/commit/de5e117909db28e789b1631925dc68b5e0f73124 by @paulomarg

**Pull request closed without merging**
